/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projectlogger;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author amina
 */
public class Application extends javax.swing.JFrame {
    private FileReader fileReader = null;
    
    /**
     * Creates new form Application
     */
    public Application() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logScrollPanel = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        logFilePanel = new javax.swing.JPanel();
        openButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        connectionPanel = new javax.swing.JPanel();
        connectButton = new javax.swing.JButton();
        disconnectButton = new javax.swing.JButton();
        measurementPanel = new javax.swing.JPanel();
        startButton = new javax.swing.JButton();
        breakButton = new javax.swing.JButton();
        exitPanel = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(350, 211));
        setName("mainFrame"); // NOI18N
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        logScrollPanel.setName(""); // NOI18N

        logTextArea.setColumns(20);
        logTextArea.setRows(10);
        logTextArea.setMinimumSize(new java.awt.Dimension(25, 22));
        logScrollPanel.setViewportView(logTextArea);

        getContentPane().add(logScrollPanel);

        logFilePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Log file"));
        logFilePanel.setMaximumSize(new java.awt.Dimension(32767, 55));

        openButton.setText("Open");
        openButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openButtonActionPerformed(evt);
            }
        });
        logFilePanel.add(openButton);

        closeButton.setText("Close");
        closeButton.setEnabled(false);
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        logFilePanel.add(closeButton);

        getContentPane().add(logFilePanel);

        connectionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Connection\n"));
        connectionPanel.setMaximumSize(new java.awt.Dimension(32767, 55));

        connectButton.setText("Connect");
        connectionPanel.add(connectButton);

        disconnectButton.setText("Disconnect");
        connectionPanel.add(disconnectButton);

        getContentPane().add(connectionPanel);

        measurementPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Measurement"));
        measurementPanel.setMaximumSize(new java.awt.Dimension(32767, 55));

        startButton.setText("Start");
        measurementPanel.add(startButton);

        breakButton.setText("Break");
        measurementPanel.add(breakButton);

        getContentPane().add(measurementPanel);

        exitPanel.setLayout(new javax.swing.BoxLayout(exitPanel, javax.swing.BoxLayout.LINE_AXIS));

        exitButton.setText("Exit");
        exitPanel.add(exitButton);

        getContentPane().add(exitPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void appendToLog(String text) {
        String oldText = logTextArea.getText();
        logTextArea.setText(oldText + "\n" + text);
     
    }
    
    private void openButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        int choice = chooser.showOpenDialog(null);
        if (choice == JFileChooser.APPROVE_OPTION) {
            try {
                fileReader = new FileReader(chooser.getSelectedFile()); 
                appendToLog("Choice: " + chooser.getSelectedFile().getName());
                closeButton.setEnabled(true);
                openButton.setEnabled(false);

            } catch (FileNotFoundException e) {
                System.out.println("File not found!");
            }        }
      //  appendToLog("Choice:" + choice);
    }//GEN-LAST:event_openButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
       if (fileReader != null) {
           try {
               fileReader.close();
               fileReader = null;
               closeButton.setEnabled(false);
               openButton.setEnabled(true);
               appendToLog("File closed.");
           } catch (IOException ex) {
               Logger.getLogger(Application.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
    }//GEN-LAST:event_closeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Application.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Application().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton breakButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton connectButton;
    private javax.swing.JPanel connectionPanel;
    private javax.swing.JButton disconnectButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel exitPanel;
    private javax.swing.JPanel logFilePanel;
    private javax.swing.JScrollPane logScrollPanel;
    private javax.swing.JTextArea logTextArea;
    private javax.swing.JPanel measurementPanel;
    private javax.swing.JButton openButton;
    private javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
